name: CI

on: [push, pull_request]

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    # Execute the checks inside the container instead the VM.
    container: golangci/golangci-lint:v1.27.0-alpine
    steps:
      - uses: actions/checkout@v1
      - run: ./hack/scripts/check.sh

  unit-test:
    name: Unit test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-go@v2-beta
        with:
          go-version: 1.14
      - run: make ci-unit-test

  integration-test:
    name: Integration test
    runs-on: ubuntu-latest
    needs: [check, unit-test]
    strategy:
      matrix:
        kubernetes: [1.16.9, 1.17.5, 1.18.2]
    env:
      KIND_VERSION: v0.8.1
    steps:
      - uses: actions/checkout@v1
      # Prepare for SSH tunnels with Serveo so we can expose the webhooks on integration tests.
      - run: mkdir -p ~/.ssh && echo -e "Host serveo.net\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
      - run: curl -Lo kind https://github.com/kubernetes-sigs/kind/releases/download/${KIND_VERSION}/kind-linux-amd64 && chmod +x kind && sudo mv kind /usr/local/bin/
      - run: curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v${{ matrix.kubernetes }}/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      - run: KUBERNETES_VERSION=${{ matrix.kubernetes }} make ci-integration-test